# Generated by Django 4.2.26 on 2025-11-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=20, unique=True)),
                ('party_leader', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_name', models.CharField(max_length=70, unique=True)),
                ('constituency_MP', models.CharField(max_length=50)),
                ('party_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='templates_demo.party')),
            ],
        ),
    ]
